# Generated by Django 4.2.6 on 2024-06-07 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryrequest",
            old_name="senderNumner",
            new_name="senderNumber",
        ),
    ]
