# Generated by Django 4.2.6 on 2024-06-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryrequest_delivered_deliveryrequest_enroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.PositiveIntegerField()),
                ('assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='rider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='delivery.rider'),
        ),
    ]
