# Generated by Django 4.2.6 on 2024-06-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_rider_deliveryrequest_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='rider',
        ),
    ]
