# Generated by Django 4.2.6 on 2024-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_deliveryrequest_rider"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrequest",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
    ]
