# Generated by Django 5.0.6 on 2024-06-15 23:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliveryrequest_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
