# Generated by Django 5.0.6 on 2024-06-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_alter_deliveryrequest_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickedUp',
            field=models.BooleanField(default=False),
        ),
    ]
