# Generated by Django 5.0.6 on 2024-06-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/shopItems')),
            ],
        ),
    ]
