# Generated by Django 4.2.6 on 2024-06-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_alter_deliveryrequest_sendernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='senderNumber',
        ),
    ]
