# Generated by Django 5.0.6 on 2024-09-20 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_shopitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('orderQuantity', models.PositiveIntegerField()),
                ('pickupNumber', models.PositiveIntegerField()),
                ('pickupPoint', models.CharField(choices=[('Select', 'Select'), ('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Takoradi', 'Takoradi'), ('Kotoridua', 'Kotoridua'), ('Ho', 'Ho'), ('Sunyani', 'Sunyani'), ('Tarkwa', 'Tarkwa'), ('Obuasi', 'Obuasi'), ('Akosombo', 'Akosombo'), ('Techiman', 'Techiman'), ('Nsawam', 'Nsawam'), ('Nkwakaw', 'Nkwakaw'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Suhum', 'Suhum'), ('Konongo', 'Konongo')], default='Select', max_length=10)),
                ('productFee', models.FloatField()),
                ('delivered', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('enroute', models.BooleanField(default=False)),
                ('pickedUp', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bulk_assignments', to='delivery.rider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkDeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryPoint', models.CharField(choices=[('Select', 'Select'), ('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Takoradi', 'Takoradi'), ('Kotoridua', 'Kotoridua'), ('Ho', 'Ho'), ('Sunyani', 'Sunyani'), ('Tarkwa', 'Tarkwa'), ('Obuasi', 'Obuasi'), ('Akosombo', 'Akosombo'), ('Techiman', 'Techiman'), ('Nsawam', 'Nsawam'), ('Nkwakaw', 'Nkwakaw'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Suhum', 'Suhum'), ('Konongo', 'Konongo')], default='Select', max_length=10)),
                ('dropoffNumber', models.PositiveIntegerField()),
                ('pickupPoint', models.CharField(choices=[('Select', 'Select'), ('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Takoradi', 'Takoradi'), ('Kotoridua', 'Kotoridua'), ('Ho', 'Ho'), ('Sunyani', 'Sunyani'), ('Tarkwa', 'Tarkwa'), ('Obuasi', 'Obuasi'), ('Akosombo', 'Akosombo'), ('Techiman', 'Techiman'), ('Nsawam', 'Nsawam'), ('Nkwakaw', 'Nkwakaw'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Suhum', 'Suhum'), ('Konongo', 'Konongo')], default='Select', max_length=10)),
                ('productFee', models.FloatField()),
                ('additionalInfo', models.TextField()),
                ('bulkDeliveryRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.bulkdeliveryrequest')),
            ],
        ),
    ]
