# Generated by Django 5.0.6 on 2024-09-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_bulkdeliveryrequest_bulkdeliverypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdeliverypoint',
            name='productFee',
        ),
    ]
