# Generated by Django 4.2.6 on 2024-06-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='enroute',
            field=models.BooleanField(default=False),
        ),
    ]
