# Generated by Django 5.0.6 on 2024-09-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_bulkdeliverypoint_deliverypoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkdeliverypoint',
            old_name='pickupPoint',
            new_name='deliveryArea',
        ),
        migrations.AddField(
            model_name='bulkdeliverypoint',
            name='Location',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkdeliverypoint',
            name='dropoffName',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
