# Generated by Django 5.0.6 on 2024-09-21 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_bulkdeliveryrequest_product_deliveryrequest_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdeliverypoint',
            name='orderQuantity',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bulkdeliverypoint',
            name='bulkDeliveryRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indv_orders', to='delivery.bulkdeliveryrequest'),
        ),
    ]
