# Generated by Django 5.0.6 on 2024-06-16 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_deliveryrequest_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
