# Generated by Django 5.0.6 on 2024-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_rider_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkdeliverypoint',
            old_name='Location',
            new_name='deliveryLocation',
        ),
        migrations.AddField(
            model_name='bulkdeliveryrequest',
            name='pickupLocation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='deliveryLocation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='dropoffName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickupLocation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
