# Generated by Django 5.0.6 on 2024-09-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_rename_location_bulkdeliverypoint_deliverylocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='deliveryLocation',
            new_name='dropoffLocation',
        ),
    ]
