# Generated by Django 5.0.6 on 2024-10-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_cartrestaurant_completed'),
        ('restaurant', '0007_food_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrestaurant',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
