# Generated by Django 5.0.6 on 2024-10-07 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_cartrestaurant_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemrestaurant',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
