# Generated by Django 4.2.6 on 2024-06-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
