# Generated by Django 5.0.6 on 2024-10-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_cartitemrestaurant_unique_id'),
        ('restaurant', '0007_food_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrestaurant',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
