# Generated by Django 4.2.6 on 2024-06-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_shopitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='senderNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
