# Generated by Django 5.0.6 on 2024-08-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_remove_deliveryrequest_sendernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
