# Generated by Django 5.0.6 on 2024-10-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_side_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='image',
            field=models.ImageField(blank=True, default='images/sides/default.png', null=True, upload_to='images/sides'),
        ),
    ]
