# Generated by Django 5.0.6 on 2024-10-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_alter_side_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='side',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
