# Generated by Django 5.0.6 on 2024-10-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_side_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideorder',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
