# Generated by Django 5.0.6 on 2024-10-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_sideorder_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdeliverypoint',
            name='orderQuantity',
        ),
        migrations.AlterField(
            model_name='cartitemrestaurant',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
