# Generated by Django 5.0.6 on 2024-10-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_remove_bulkdeliverypoint_orderquantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdeliveryrequest',
            name='productFee',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='productFee',
        ),
        migrations.AlterField(
            model_name='bulkdeliverypoint',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
