# Generated by Django 5.0.6 on 2024-10-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_remove_bulkdeliveryrequest_productfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdeliverypoint',
            name='deliveryPoint',
            field=models.CharField(choices=[('Select', 'Select'), ('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Takoradi', 'Takoradi'), ('Koforidua', 'Koforidua'), ('Ho', 'Ho'), ('Sunyani', 'Sunyani'), ('Tarkwa', 'Tarkwa'), ('Obuasi', 'Obuasi'), ('Akosombo', 'Akosombo'), ('Techiman', 'Techiman'), ('Nsawam', 'Nsawam'), ('Nkwakaw', 'Nkwakaw'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Suhum', 'Suhum'), ('Konongo', 'Konongo'), ('AccraAccra', 'Accra')], default='Select', max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='deliveryPoint',
            field=models.CharField(choices=[('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Takoradi', 'Takoradi'), ('Koforidua', 'Koforidua'), ('Ho', 'Ho'), ('Sunyani', 'Sunyani'), ('Tarkwa', 'Tarkwa'), ('Obuasi', 'Obuasi'), ('Akosombo', 'Akosombo'), ('Techiman', 'Techiman'), ('Nsawam', 'Nsawam'), ('Nkwakaw', 'Nkwakaw'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Suhum', 'Suhum'), ('Konongo', 'Konongo'), ('Accra', 'Accra')], default='Kumasi', max_length=10),
        ),
    ]
