# Generated by Django 5.0.6 on 2024-10-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_alter_bulkdeliverypoint_deliverypoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdeliverypoint',
            name='deliveryPoint',
            field=models.CharField(choices=[('AccraAccra', 'Accra'), ('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Takoradi', 'Takoradi'), ('Koforidua', 'Koforidua'), ('Ho', 'Ho'), ('Sunyani', 'Sunyani'), ('Tarkwa', 'Tarkwa'), ('Obuasi', 'Obuasi'), ('Akosombo', 'Akosombo'), ('Techiman', 'Techiman'), ('Nsawam', 'Nsawam'), ('Nkwakaw', 'Nkwakaw'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Suhum', 'Suhum'), ('Konongo', 'Konongo')], default='AccraAccra', max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='deliveryPoint',
            field=models.CharField(choices=[('Accra', 'Accra'), ('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Takoradi', 'Takoradi'), ('Koforidua', 'Koforidua'), ('Ho', 'Ho'), ('Sunyani', 'Sunyani'), ('Tarkwa', 'Tarkwa'), ('Obuasi', 'Obuasi'), ('Akosombo', 'Akosombo'), ('Techiman', 'Techiman'), ('Nsawam', 'Nsawam'), ('Nkwakaw', 'Nkwakaw'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Suhum', 'Suhum'), ('Konongo', 'Konongo')], default='Accra', max_length=10),
        ),
    ]
