# Generated by Django 5.0.6 on 2024-10-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0029_deliveryrequest_deliveryspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdeliverypoint',
            name='deliverySpeed',
            field=models.CharField(choices=[('Same day delivery', 'Same day delivery'), ('Next day delivery', 'Next day delivery'), ('Express delivery', 'Express delivery')], default='Same day delivery', max_length=17),
        ),
    ]
