# Generated by Django 5.0.6 on 2024-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0030_bulkdeliverypoint_deliveryspeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdeliveryrequest',
            name='product',
        ),
        migrations.AddField(
            model_name='bulkdeliverypoint',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
