# Generated by Django 5.0.6 on 2024-10-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0031_remove_bulkdeliveryrequest_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkdeliverypoint',
            name='product',
        ),
        migrations.AddField(
            model_name='bulkdeliveryrequest',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
