# Generated by Django 5.0.6 on 2025-03-08 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0032_remove_bulkdeliverypoint_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrIdent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reqeustType', models.CharField(blank=True, max_length=255, null=True)),
                ('bulkDeliveryRequest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.bulkdeliveryrequest')),
                ('deliveryRequest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryrequest')),
            ],
        ),
    ]
