# Generated by Django 5.0.6 on 2025-02-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0032_remove_bulkdeliverypoint_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdeliveryrequest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
