# Generated by Django 5.0.6 on 2025-03-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0034_remove_qrcodedata_qr_code_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QrCodeData',
            new_name='QrCodeD',
        ),
    ]
