# Generated by Django 5.0.6 on 2025-03-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0034_delete_shopitem_deliveryrequest_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrident',
            old_name='reqeustType',
            new_name='requestType',
        ),
    ]
