# Generated by Django 5.0.6 on 2025-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0035_rename_reqeusttype_qrident_requesttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdeliveryrequest',
            name='deliveryFee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bulkdeliveryrequest',
            name='orderQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
