# Generated by Django 5.0.6 on 2025-03-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0035_rename_qrcodedata_qrcoded'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcoded',
            name='reqeustType',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
