# Generated by Django 5.0.6 on 2025-03-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0036_qrcoded_reqeusttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcoded',
            name='reqeustType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
