# Generated by Django 5.0.6 on 2025-03-15 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0037_alter_bulkdeliveryrequest_deliveryfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkdeliveryrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
