# Generated by Django 5.0.6 on 2025-03-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0039_alter_bulkdeliverypoint_deliverypoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdeliverypoint',
            name='deliveryPoint',
            field=models.CharField(choices=[('Kumasi', 'Kumasi'), ('Accra', 'Accra'), ('Sunyani', 'Sunyani'), ('Takoradi', 'Takoradi'), ('Koforidua', 'Koforidua'), ('Techiman', 'Techiman'), ('Tamale', 'Tamale')], default='Kumasi', max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='deliveryPoint',
            field=models.CharField(choices=[('Kumasi', 'Kumasi'), ('Accra', 'Accra'), ('Sunyani', 'Sunyani'), ('Takoradi', 'Takoradi'), ('Koforidua', 'Koforidua'), ('Techiman', 'Techiman'), ('Tamale', 'Tamale')], default='Kumasi', max_length=10),
        ),
    ]
