# Generated by Django 5.0.6 on 2024-09-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
