# Generated by Django 5.0.6 on 2024-09-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
    ]
