# Generated by Django 5.0.6 on 2024-09-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_rename_deliverylocation_deliveryrequest_dropofflocation'),
        ('home', '0006_profile_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rider',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.rider'),
        ),
    ]
