# Generated by Django 5.0.6 on 2024-10-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default='food_images/images.png', null=True, upload_to='food_images/'),
        ),
    ]
