# Generated by Django 5.0.6 on 2024-10-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_food_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='unique_id',
        ),
    ]
