# Generated by Django 5.0.6 on 2024-10-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_sideorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
